name: CI/CD

on:
  push:
    branches: ["main"]

jobs:
  # =========================
  # CI JOB
  # =========================
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@master
        with:
          root: .

      - name: Security check
        run: |
          if ls *.env 2>/dev/null; then
            echo "‚ùå .env file found"
            exit 1
          else
            echo "‚úÖ No sensitive files"
          fi

      - name: Build Docker image (CI test build)
        run: docker build -t static-site:ci .

      - name: Run container
        run: |
          docker run -d -p 8080:80 --name test-site static-site:ci
          sleep 5

      - name: Integration test
        run: curl -f http://localhost:8080

      - name: CI completed
        run: echo "‚úÖ CI passed successfully"

  # =========================
  # CD JOB (FULLY AUTOMATED)
  # =========================
  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          IMAGE=ghcr.io/zehroozmirza/amazon-clone:${{ github.sha }}
          docker build -t $IMAGE .

      - name: Push Docker image to GHCR
        run: |
          IMAGE=ghcr.io/zehroozmirza/amazon-clone:${{ github.sha }}
          docker push $IMAGE

      # üîê Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ 8ba80c58-dfdc-4771-b2c3-2b90e3817dc3 }}
          tenant-id: ${{ 9a6a0a9c-fe46-42a9-80eb-d5048872f6ce}}
          subscription-id: ${{ 59842674-7540-4d56-8769-2fbd86a14b17 }}

      # üöÄ Deploy to Azure Web App (Container)
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: ghcr.io/zehroozmirza/amazon-clone:${{ github.sha }}

      - name: CD completed
        run: echo "üöÄ Deployed to Azure Web App successfully"
