name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# REQUIRED for pushing images to GHCR
permissions:
  contents: read
  packages: write

jobs:
  # =========================
  # CI JOB
  # =========================
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@master
        with:
          root: .

      - name: Install CSS linter
        run: npm install -g stylelint stylelint-config-standard


      - name: Security check
        run: |
          if ls *.env 2>/dev/null; then
            echo "‚ùå .env file found"
            exit 1
          else
            echo "‚úÖ No sensitive files"
          fi

      - name: Build Docker image (CI test build)
        run: docker build -t static-site:ci .

      - name: Run container
        run: |
          docker run -d -p 8080:80 --name test-site static-site:ci
          sleep 5

      - name: Integration test
        run: curl -f http://localhost:8080

      - name: CI completed
        run: echo "‚úÖ CI passed successfully"

  # =========================
  # CD JOB
  # =========================
  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image for registry
        run: |
          IMAGE=ghcr.io/zehroozmirza/amazon-clone:${{ github.sha }}
          docker build -t $IMAGE .

      - name: Push Docker image to GHCR
        run: |
          IMAGE=ghcr.io/zehroozmirza/amazon-clone:${{ github.sha }}
          docker push $IMAGE

      - name: CD completed
        run: echo "üöÄ Docker image pushed to GHCR successfully"
